### ISSUE TITLE
Interpretation output

### ISSUE THREAD

**Issue by dottoreD** [triq-org/revdgst#4]
I worked with examples and got following output from revdgst when playing around with subgroups. I found no way how to interpret the results, maybe you can give a bit of support to understand, the first two lines are clear of course.
Below is only start of output

br,
Dieter
```
Code len is 4 bytes (8 nibbles), 10 codes read.
Processing...
Done with g 00 k 00 final XOR 01 using sum xor (100 %)
Done with g 00 k 00 final XOR 01 using sum xor (100 %)
Done with g 00 k 00 final XOR 01 using xor xor (100 %)
Done with g 00 k 00 final XOR 01 using sum add (100 %)
Done with g 00 k 00 final XOR 01 using xor add (100 %)
Done with g 00 k 00 final XOR ff using sum sub (100 %)
Done with g 00 k 00 final XOR ff using xor sub (100 %)
.
.
.
````

**Comment by zuckschwerdt** [comment]
E.g., first line: that reports that 100% of input codes can be checked successful with a generator of `00`, key of `00`, using sum (adding with carry) as the summation step and comparing to the checksum field with xor after applying a final xor of `01` (all values hex).
It looks like your last byte is a fixed value?

**Comment by dottoreD** [comment]
I worked with a special subpart of fletcher.txt. When I have added some other data with the same last byte, the percentage decreased, which was expected.
But I cannot recalculate the result by my own, maybe because I don't understand formula behind. All my trials to manually calculate ended with not the same result for each line.
Doing that what I understood what you said above, I receive in decimal `37` for first line and `15` for second line.

`; this data shows xor-sum (or parity) on the last nibble
; the next-to-last nibble seems addition, this might be a flechter-scheme.
;
f802b001
0a130001
0754a001
0574e001
fe942001
08c3b001
08d3a001
08e39001
fbe20001
03f4c001
`
added values not fitting into above scheme, but same last byte
`ff120001
00346001
0893d001
07b47001
`

**Comment by zuckschwerdt** [comment]
The output above is from `revdgst` which tries to find a keystream for a digest. That means a key for every bit so the sum of all keys for `1` bits equals the last byte. It won't work for any other scheme, and the last byte needs to be a digest / last two bytes for `revdgst16` -- but it's fixed `01` in this example.
The `revsum` code is the one checking for other schemes, like fletcher -- but you need to strip fixed trailing bytes.

**Comment by zuckschwerdt** [comment]
Oh, I see now. data_fletcher.txt has one more byte not shown here ;) That is important.

**Comment by zuckschwerdt** [comment]
And we so far haven't found the checksum solution to those codes.

**Comment by dottoreD** [comment]
OK So it will also not work for 4Bit nibble digest as for `f802b001 1`?

And my trial to I add first nibble digest from fletcher.txt for those, and repeated revdgst was nonsense? Because I receive the following, so the same problem for me to understand what the algorithm is that creates the solution, or redo manually.

Code len is 5 bytes (9 nibbles), 10 codes read.
Processing...
Done with g 00 k 00 final XOR 10 using sum xor (100 %)
Done with g 00 k 00 final XOR 10 using sum xor (100 %)

If above is right that it doesn't work for nibbles, is there a solution for that? Programming a revdgst for 4Bit would be above my knowledge.

As I have not been able to generate final nibble following description in the file, I tried something manually that seems to work in my understanding: xor for second, forth, six nibble, final xor with magic "3". Pretty simple I think.
My idea was to take that and then to try if it can be verified by any of the tool methods. But I wanted to have solution for both checksum nibbles first.

**Comment by zuckschwerdt** [comment]
The output "g 00 k 00" is not a proper digest. (start at 0, change by xor 0 for every bit) -- it's just blank `0`.

You should be able to use shorter digests by padding and blanking. E.g. `f802b001 01` or `f802b001 10` depending on the roll direction the algorithm is going. But a Digest-4 has a maximum of 15 keys, trivial to trace by hand I'd say.

And a digest can't produce any random sequence of keys (needs to be some LFSR), so picking 15 or even 16 keys by hand should work better.

**Comment by zuckschwerdt** [comment]
I usually use `bitbrk` for that, it highlights messages with a single-bit difference, the first output column is the xor, thus the key for that bit. Check that it's consistent for all message pairs with that single bit difference. And repeat.

**Comment by dottoreD** [comment]
Hmm, if I don't bother you maybe we can speak about the Codes from data_fletcher.txt. Did you looked on proposed algorithm to calculate the very last nibble? If this makes sense, why not considering 2 algorithms, one for each nibble? It took me a while to see that not each data nibble is used for the hash. With simple Xor. Unfortunately not trivial, for me.
That was the reasons for me to see, if one of the tools can do it more simple.
And, I think the checksum nibbles are not randomly distributed, I would say a higher population of `1` at both of them. So the method is not perfect.

The use and output of `bitbrk` has been a big mystery for me until now.

**Comment by zuckschwerdt** [comment]
I can't remember where that data_fletcher.txt came from. It's a special (and unsolved) case and wasn't interesting enough, I guess.
Do you have a particular reason to look into those codes specifically?

Look at [this BitBench](https://triq.net/bitbench#c=00346001%2026&c=0091f001%20e3&c=01748001%20b7&c=0251e001%2051&c=0274a001%20c4&c=0344b001%20d5&c=03f4c001%2015&c=0471c001%20f7&c=0484d001%20e2&c=04f4e001%20a2&c=0574e001%2013&c=05e4e001%2083&c=0654e001%2060&c=06a4d001%20a0&c=06b1a001%2035&c=06e4d001%20e0&c=0724c001%2001&c=0754a001%2011&c=07849001%20f1&c=07b47001%2021&c=07d45001%2061&c=08044001%20be&c=08242001%20fe&c=08441001%20ae&c=0863f001%20f9&c=0873e001%20f9&c=0893d001%2029&c=08a3c001%2009&c=08c3b001%2019&c=08d21001%2098&c=08d3a001%2019&c=08e39001%2019&c=0a030000%203a&c=0a12e001%20ca&c=0a130001%201b&c=f7323001%20b7&c=f7423001%20c7&c=f802b001%2018&c=fa533001%209b&c=fb220001%20db&c=fbe20001%201b&c=fca3b001%204d&c=fcc20001%20ac&c=fdd20001%208d&c=fe942001%2018&c=ff120001%202f&f=8h8h%208h8h%208h&cf=XOR&cl=40&cw=8), it shows why I suspect xor-summation.

**Comment by dottoreD** [comment]
My interest was that this file was said to have checksum split into nibbles, not byte which is normal case. I have a dataset in nibbles too, including digest. And I wanted to see some other data, learn from them and maybe have some additional ideas for my original problem.

**Comment by dottoreD** [comment]
Why do you have used the magic numbers length=40 and width=8? I've seen that parameter, but was not able to use values with some ratio behind.

**Comment by zuckschwerdt** [comment]
> checksum split into nibbles, not byte which is normal case

If you pad any data and checksum to whole bytes the tools here should mostly work.

> Why do you have used the magic numbers length=40 and width=8?

That's just a bit-width, the message length in (5 bytes) and the byte length (8 bits), some sums would be of width 1 bit (parity) or width 4 bit (nibble sums).

**Comment by dottoreD** [comment]
Thanks, with that information I've been now able to get suitable output.

This might be offtopic here, but you said, having a 4Bit Hash would be most likely trivial to trace by hand. So I feel a bit stupid, having just 5 nibbles of data and 1 nibble hash, and there is some logic behind. But I cannot catch it.
This are the data, just when you like, 3 parts from bigger dataset. First part looks easy but maybe misleading and the only one I got any result with the tools

```
000C54
0013AA
002C56
0033A8
004C50
0053AE
006C52
0073AC
008C5C
0093A2
00AC5E
00B3A0
00CC58
00D3A6
00EC5A
00F3A4
```

the second here looks similar, but there is a difference
```
050C5E
0513A0
052C5D
0533A3
054C58
0553A6
056C5A
0573A4
058C54
0593AA
05AC56
05B3A8
05CC53
05D3AD
05EC50
05F3AE
```

And for this third part I'm completely out
```
0A0C5E
0A13A0
0A2C5D
0A33A3
0A4C58
0A53A6
0A6C5A
0A73A4
0A8C53
0A93AD
0AAC51
0AB3AF
0ACC57
0AD3A9
0AEC55
0AF3AB
```

**Comment by zuckschwerdt** [comment]
Drop the leading nibble and add one before the check, e.g. `0AF3AB -> AF3A 0B`
If you now run `bitbrk`, then you get a consistent mask of `8` for bit 4 (original bit 8, we dropped a nibble), but that changes when bits appear to the left of that position:
```
 4 : 00 c5 04  ->  08 c5 0c  |  08
 4 : 01 3a 0a  ->  09 3a 02  |  08
 4 : 02 c5 06  ->  0a c5 0e  |  08
 4 : 03 3a 08  ->  0b 3a 00  |  08
 4 : 04 c5 00  ->  0c c5 08  |  08
 4 : 05 3a 0e  ->  0d 3a 06  |  08
 4 : 06 c5 02  ->  0e c5 0a  |  08
 4 : 07 3a 0c  ->  0f 3a 04  |  08
 4 : 50 c5 0e  ->  58 c5 04  |  0a
 4 : 51 3a 00  ->  59 3a 0a  |  0a
 4 : 52 c5 0d  ->  5a c5 06  |  0b
 4 : 53 3a 03  ->  5b 3a 08  |  0b
```
So this code is based on xor but modifies the state of the mask with probably each 1-bit. That's basically what we expect from a CRC or LFSR digest.
It's linear though (counting up) like a sum, not what a CRC or LFSR would show.
That indicates, like you found, something like a Fletcher scheme.

It's xor based and there is some carry or state setup or shift register. With enough codes you can likely trace where the bits go --  it's just 16 bit to 4 bit here, no big number crunching needed ;)
It's complicated though which direction to work, a simple "there is a mask that changes the checksum if a bit is 1, also the mask changes if the bit is 1" can't be easily applied left-to-right or right-to-left here.
But this might also be deceptive, as we only get bit-collision for codes ending in `3a` and `c5` which are inverse, so that might play a role here too...

**Comment by zuckschwerdt** [comment]
It would be interesting to get multiple codes with single bit changes in the first or last bit in the first or last nibble. Then see if that get consistent mask. That way you can figure out which order the bits are processed (and thus the direction the mask change travels).

**Comment by dottoreD** [comment]
Starting from the back. I have about 900 codes, first nibble 0-F, second nibble 0,2,5,8,A,D,F, third nibble 0-F, but not fully populated and with some gaps, uploaded at https://github.com/dottoreD/rtl_433_tests/blob/master/tests/Eberle/Instat%20868r1/learn.txt
For the rest I need to read again, digest and understand and do some tests.

**Comment by zuckschwerdt** [comment]
Ok, so we can observe bit 0, 1, 2, 3, 4, 6, 8, 9, 10 change. None of those is a fixed checksum mask, so not the start position of a moving mask :/ But bit 2 and 10 vary less (mask is only ever 2 or 3), well...

I would now take this list and condense it to rules like a `1` in bit 0 applies X to the checksum for codes (ignore the 3a/c5 for now):
```
000 -> f
001 -> f
002 -> f
003 -> f
004 -> f
005 -> f
006 -> f
007 -> f
008 -> b
009 -> b
00a -> a
00b -> a
00c -> 8
00d -> 8
00e -> 8
00f -> 8

050 -> a
051 -> a
052 -> b
053 -> b
054 -> 8
055 -> 8
056 -> 8
057 -> 8
058 -> f
059 -> f
05a -> f
05b -> f
05c -> f
05d -> f
05e -> f
05f -> f
```

There is obviously a pattern, but neither linear nor directional. Looks like lots of work...

**Comment by dottoreD** [comment]
Still working to understand your explanations, but your summary for pattern is exactly as mine. Hopefully with your expertise it is easier to find what is behind that pattern, because my theoretic knowledge in that is very low and I have to work more experimental by trial and error. For that reason I had arranged the codes and keys in a matrix. Then a pattern is obvious, but no chance how key is generated. I wish, I could give any other good input.

I cannot say for sure, but as the length is so small, and there is a good number of codes number crunching sounds not bad in my ears.

**Comment by dottoreD** [comment]
Meanwhile I read "painless guide to CRC" to understand something more about theory behind, which now explains to me some of the modules in `revdgst` and `revsum` for reflecting and reversing. As you said CRC could be excluded, right? Because I found some kind of number cruncher software for CRC called `reveng`, but which is useless in that case.

**Comment by zuckschwerdt** [comment]
The changes don't show enough entropy, they are mostly linear, that's not CRC.

**Comment by dottoreD** [comment]
I created a table with xx0xxx - xxFxxx per row, and a single row for each one from 00xxxx to FFxxxxx, showing that the sequence of hashes for xx0-xxF is the same in a few cases. By example 
```
1A0 C5 0 | … | 1AF 3A 0
400 C5 0 | … | 40F 3A 0
920 C5 0 | … | 92F 3A 0
EA0 C5 0 | … | EAF 3A 0
```
are exactly the same. Typically 2 or 3 lines are identical. Could this be useful for some analysis?

**Comment by dottoreD** [comment]
And maybe some other pattern of interest: when I mask nibble#5 the XOROUT becomes more simple and will be the same for the full row, by example 00...; 65...; CD...; D2...; 22...; 95...; 8A...
For all others it's not the case, so a simple XOR for all nibble doesn't suffice, but none of them is random, all show some pattern. Some with symmetry, some not.

I would like to do some trial&error testing on that, but I don't know how to start with and if this really can have success.
And one more pattern thing: in a few cases the XOROUT pattern AND checksum is exactly the same, for example with 40..;EA..

**Comment by zuckschwerdt** [comment]
> xx0 C5 0 | … | xxF 3A 0
> are exactly the same. Typically 2 or 3 lines are identical. Could this be useful for some analysis?

That is interesting, because 0xc ^ 0x5 == 0x3 0xa, but 0x0 is inverse of 0xf.
This means the `0` / `F` set up the mask so 0xC5 / 0x3A do the opposite thing (and get the same end-result)

**Comment by dottoreD** [comment]
That was a misunderstanding, this is not true not for all 
` xx0 C5 0 | … | xxF 3A 0
`

only for above cases, total table is that one
`
400C50 4013AE 402C53 4033AD 404C56 4053A8 406C54 4073AA 408C5A 4093A4 40AC58 40B3A6 40CC5D 40D3A3 40EC5E 40F3A0
EA0C50 EA13AE EA2C53 EA33AD EA4C56 EA53A8 EA6C54 EA73AA EA8C5A EA93A4 EAAC58 EAB3A6 EACC5D EAD3A3 EAEC5E EAF3A0
1A0C50 1A13AE 1A2C53 1A33AD 1A4C56 1A53A8 1A6C54 1A73AA 1A8C5A 1A93A4 1AAC58 1AB3A6 1ACC5D 1AD3A3 1AEC5E 1AF3A0
920C50 9213AE 922C53 9233AD 924C56 9253A8 926C54 9273AA 928C5A 9293A4 92AC58 92B3A6 92CC5D 92D3A3 92EC5E 92F3A0
`

**Comment by dottoreD** [comment]
One more thinking on patterm information: for all pairs of xx0xxM | xx1xxN, xx2xxO | xx3xxP, ..., xxExxQ | xxFxxR I've found that M ^ N == D ... Q ^ R == D. So there is some symmetry in those pairs, and when algorithm for even Nibble3 is found, the odd paired one is also solved. However there are still some patterns for which I have no idea how these come up.
